---
# handlers file for tomcat-multi
- name: restart NGINX
  sudo: yes
  service: name=nginx state=restarted

- name: restart tomcat
  sudo: yes
  service: name=tomcat{{ tomcat.version }} state=started
